name: CI/CD 

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ] 
  workflow_dispatch:

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Java 11 (Back)
        uses: actions/setup-java@v4.4.0
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Installer Node.js 18 (Front)
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Installer les dépendances du Back
        run: |
          cd back
          mvn clean install

      - name: Lancer les tests du Back avec couverture
        run: |
          cd back
          mvn test
          mvn jacoco:report

      - name: Installer les dépendances du Front
        run: |
          cd front
          npm install

      - name: Lancer les tests du Front avec couverture
        run: |
          cd front
          npm test -- --code-coverage --watch=false --browsers=ChromeHeadless

      - name: Vérifier la couverture du Front
        run: |
          ls -R front/coverage

      - name: Upload du rapport JaCoCo (HTML)
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-html-report
          path: back/target/site/

      - name: Upload du rapport Karma (HTML)
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: karma-coverage-html
          path: front/coverage/bobapp/index.html  

      - name: Ajouter le rapport de couverture JaCoCo dans la PR
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: back/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 30
          min-coverage-changed-files: 60
      
      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v3.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          extraArgs: |
            -Dsonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml
            -Dsonar.javascript.lcov.reportPaths=front/coverage/bobapp/lcov.info