name: CI/CD 
on:
  pull_request:
    paths-ignore: ['**.md']
  push:
    paths-ignore: ['**.md']
    branches:
      - main
  workflow_dispatch:

permissions:
  actions: read
  checks: write

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Java 11 (Back)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Installer Node.js 18 (Front)
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Installer les dépendances du Back
        run: |
          cd back
          mvn clean install

      - name: Lancer les tests du Back avec couverture
        run: |
          cd back
          mvn test
          mvn jacoco:report

      - name: Installer les dépendances du Front
        run: |
          cd front
          npm install

      - name: Lancer les tests du Front avec couverture
        run: |
          cd front
          npm test -- --code-coverage --watch=false --browsers=ChromeHeadless

      - name: Upload Jacoco Report (Back)
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: back/target/site/jacoco/jacoco.xml

      - name: Upload Karma Coverage Report (Front)
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: karma-coverage
          path: front/coverage/coverage.xml

      - name: Test Report
        uses: phoenix-actions/test-reporting@v8
        id: test-report
        if: success() || failure()
        with:
          name: Test Coverage
          path: |
            back/target/site/jacoco/jacoco.xml
            front/coverage/coverage.xml
          reporter: jacoco