name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build back Docker image
        run: |
          docker build -f back/Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/bobapp-back:${{ github.sha }} back/
        
      - name: Push back Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/bobapp-back:${{ github.sha }}

      - name: Build front Docker image
        run: |
          docker build -f front/Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/bobapp-front:${{ github.sha }} front/
        
      - name: Push front Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/bobapp-front:${{ github.sha }}
